### ISSUE TITLE
Che s'adda fa

### ISSUE THREAD

**Issue by Xiradorn** [clalulu/MSC_schedule#1]
Bene bene bene bene. Allora fammi capire una cosa. Nella parte di applicativo web io vedo le seguenti cose:  
**index.jsp - Login.js - Login.jsp - web.xml**

Mo fammi capire ste cose:
- Che si deve creare e o modificare?
- Le pagine funzionano già?
- il login te lo fa già?
- Si deve aggiungere qualcosa?

Fammi sapere come vuoi procede

**Comment by clalulu** [comment]
allora nn funziona na ceppa perche devo implementare bene la parte java. la
cosa che dobbiamo modificare appena funziona qualcosa è login.jsp inserendo
dei jquery per abbellirlo. la cosa importante e lunga da fare e la pagina
index.jsp che adesso nn è altro una pagina di prova con la scritta hello
world. quindi bisogna sostituire le index.jsp con quella pagina che ti ho
spiegato con lo schedule, sezione administrator e sezione grafici.

-------Messaggio originale-------

Da: Tony Frost
Data: 07/07/15 20:24:47
A: clalulu/MSC_schedule
Oggetto: [MSC_schedule] Che s'adda fa (#1)

Bene bene bene bene. Allora fammi capire una cosa. Nella parte di
applicativo web io vedo le seguenti cose:

index.jsp - Login.js - Login.jsp - web.xml
Mo fammi capire ste cose:
Che si deve creare e o modificare? 
Le pagine funzionano già? 
il login te lo fa già? 
Si deve aggiungere qualcosa? 
Fammi sapere come vuoi procede
